---

- name: Import per OS variables
  include_vars: vars-deb.yml

- name: Remove conflicting packages
  apt:
    name: "{{ docker_conflicting_packages }}"
    state: absent
  when: docker_remove_conflicting_packages

- name: Install prerequisities
  apt:
    name: apt-transport-https
    cache_valid_time: 900

- name: Install Docker repo GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable"
    filename: docker
    update_cache: yes

# - name: Install Docker
#   apt:
#     name:
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#   notify:
#     - start docker
