{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y python3 sudo bash ca-certificates iproute2 python3-apt aptitude gnupg systemd systemd-sysv && apt-get clean && rm -rf /var/lib/apt/lists/*; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3 sudo bash iproute systemd systemd-sysv findutils && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute systemd systemd-sysv && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; fi

# Don't start any optional services.
RUN find /etc/systemd/system \
        /lib/systemd/system \
        -path '*.wants/*' \
        \( -name '*getty*' \
        -or -name '*apt-daily*' \
        -or -name '*systemd-timesyncd*' \
        -or -name '*systemd-logind*' \
        -or -name '*systemd-vconsole-setup*' \
        -or -name '*systemd-readahead*' \
        -or -name '*kdump*' \
        -or -name '*dnf-makecache*' \
        -or -name '*udev*' \) \
        -exec rm -v \{} \; && \
    systemctl set-default multi-user.target && \
    systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount network.service
