---
- name: Prepare
  hosts: all
  tasks:
    - name: Update APT cache
      apt:
        cache_valid_time: 900
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Add test user
      user:
        name: dude
        comment: Some Dude
